{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2019-08-13T15:45:33.014442Z",
     "start_time": "2019-08-13T15:45:32.093519Z"
    }
   },
   "outputs": [],
   "source": [
    "import os\n",
    "import sys\n",
    "import config as cfg\n",
    "import time\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2019-08-13T15:45:33.036627Z",
     "start_time": "2019-08-13T15:45:33.033718Z"
    }
   },
   "outputs": [],
   "source": [
    "PROJECT_NAME = 'TimeSeriesKb'\n",
    "PROJECT_START_DATE = 'start date' #ENGLISH DATE FORMAT\n",
    "PROJECT_END_DATE = '' #ENGLISH DATE FORMAT"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2019-08-13T15:45:33.063963Z",
     "start_time": "2019-08-13T15:45:33.053071Z"
    },
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The haribo package provides the following functions to use in Jupyter:\n",
      "\n",
      "set_screen_width() - sets cells to be 90% of screen width\n",
      "\n",
      "show_df(dataFrame, allRows = False) - shows all columns of a dataFrame when displayed\n",
      "\n",
      "pickle_it(data, path) - safely pickles a file\n",
      "\n",
      "from_pickle_jar(path) - safely loads a pickled file\n",
      "\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<style>.container { width:90% !important; }</style>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "#ROOT, PROJECT_ROOT, PACKAGE_ROOT = config.configure_environment('Local',PROJECT_NAME)\n",
    "\n",
    "config = cfg.privateConfig(cfg.OS, PROJECT_NAME)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2019-08-13T15:45:33.094050Z",
     "start_time": "2019-08-13T15:45:33.082447Z"
    }
   },
   "outputs": [],
   "source": [
    "from DataCrane.dbutility import gnrl_database_interaction as gdbi\n",
    "from DataCrane.dbutility import credentials\n",
    "from CodeCandy.haribo import jupyter as candy"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Create a connection object"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2019-08-13T15:45:33.779952Z",
     "start_time": "2019-08-13T15:45:33.771482Z"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/Users/chrispickford/Documents/Coding/Python/Projects/TimeSeriesKb/Jupyter\n",
      "/Users/chrispickford/Documents/Coding/Python/Projects/TimeSeriesKb/Logs\n",
      "TimeSeriesKb.log\n",
      "Log file name specified: TimeSeriesKb.log\n",
      "Log file set:  /Users/chrispickford/Documents/Coding/Python/Projects/TimeSeriesKb/Logs/TimeSeriesKb.log\n",
      "crafty-ring-247514\n"
     ]
    }
   ],
   "source": [
    "logFileName = PROJECT_NAME + '.log'\n",
    "_ = config.set_logging(logFileName)\n",
    "\n",
    "newUser = cfg.credentials()\n",
    "\n",
    "connection = gdbi.GBQConnection(config, credentials=newUser,logFileName=logFileName,useLegacy=False, projectId='crafty-ring-247514',if_exists='replace') # push to BQ"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Create a connection object handler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2019-08-13T15:46:04.764471Z",
     "start_time": "2019-08-13T15:46:04.749329Z"
    }
   },
   "outputs": [],
   "source": [
    "sqlConnection = gdbi.ExecuteSQL(\n",
    "    connection=connection, \n",
    "    query = pd.read_csv(os.path.join(config.PROJECT_ROOT,'Data','forecast.csv'),names=['Date','Forecasted','HeadCount','SquareError','mse','RMSE','difference'],header=0),\n",
    "    outputPath=None\n",
    ")\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Push data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2019-08-13T15:46:10.554859Z",
     "start_time": "2019-08-13T15:46:05.595196Z"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Kickboxing_attendance.forecast\n",
      "crafty-ring-247514\n",
      "Executing script:\n",
      "           Date    Forecasted  HeadCount   SquareError          mse       RMSE  \\\n",
      "0   2018-10-07  2.784106e+02        312  1.128246e+03  1128.246458  33.589380   \n",
      "1   2018-10-14  2.537328e+02        226  7.691088e+02   948.677636  30.800611   \n",
      "2   2018-10-21  2.125079e+02        207  3.033706e+01   642.564111  25.348848   \n",
      "3   2018-10-28  1.790045e+02        172  4.906247e+01   494.188700  22.230355   \n",
      "4   2018-11-04  1.227529e+02        102  4.306823e+02   481.487417  21.942822   \n",
      "5   2018-11-11  1.672398e+02        189  4.735084e+02   480.157573  21.912498   \n",
      "6   2018-11-18  1.629747e+02        174  1.215570e+02   428.928922  20.710599   \n",
      "7   2018-11-25  1.487371e+02        153  1.817194e+01   377.584300  19.431529   \n",
      "8   2018-12-02  1.679953e+02        144  5.757737e+02   399.605346  19.990131   \n",
      "9   2018-12-09 -5.470034e+00         78  6.967247e+03  1056.369464  32.501838   \n",
      "10  2018-12-16  1.881191e+01         61  1.779835e+03  1122.139028  33.498344   \n",
      "11  2018-12-23  1.550383e+01          0  2.403688e+02  1048.658178  32.382992   \n",
      "12  2018-12-30  5.378380e-14          0  2.892697e-27   967.992165  31.112572   \n",
      "13  2019-01-06 -6.226940e-28          0  3.877478e-55   898.849867  29.980825   \n",
      "14  2019-01-13  9.481906e-27         40  1.600000e+03   945.593209  30.750499   \n",
      "15  2019-01-20  4.202022e+01         17  6.260114e+02   925.619346  30.423993   \n",
      "16  2019-01-27  4.630038e+01         22  5.905084e+02   905.906935  30.098288   \n",
      "17  2019-02-03  5.205450e+01        117  4.217918e+03  1089.907561  33.013748   \n",
      "18  2019-02-10  1.549801e+02        128  7.279257e+02  1070.855886  32.723934   \n",
      "19  2019-02-17  1.529438e+02         94  3.474373e+03  1191.031726  34.511328   \n",
      "20  2019-02-24  1.112445e+02        116  2.261444e+01  1135.392808  33.695590   \n",
      "21  2019-03-03  1.056311e+02        104  2.660339e+00  1083.904968  32.922712   \n",
      "22  2019-03-10  1.190521e+02        101  3.258801e+02  1050.947365  32.418318   \n",
      "23  2019-03-17  1.284925e+02        113  2.400167e+02  1017.158588  31.892924   \n",
      "24  2019-03-24 -4.766883e+00         90  8.980762e+03  1335.702731  36.547267   \n",
      "25  2019-03-31  2.081109e+01        102  6.591639e+03  1537.854140  39.215483   \n",
      "26  2019-04-07  2.628242e+01        122  9.161856e+03  1820.224575  42.664090   \n",
      "27  2019-04-14  3.558609e+01          0  1.266370e+03  1800.444045  42.431640   \n",
      "28  2019-04-21  9.000000e+01          0  8.100000e+03  2017.670113  44.918483   \n",
      "29  2019-04-28  5.404650e+01         22  1.026978e+03  1984.647044  44.549378   \n",
      "30  2019-05-05  7.366518e+01         84  1.068086e+02  1924.071610  43.864241   \n",
      "31  2019-05-12  7.229179e+01         62  1.059210e+02  1867.254405  43.211739   \n",
      "32  2019-05-19  7.358114e+01         38  1.266017e+03  1849.035099  43.000408   \n",
      "33  2019-05-26  4.783548e+01         36  1.400785e+02  1798.771671  42.411928   \n",
      "34  2019-06-02  5.038190e+01         40  1.077838e+02  1750.457733  41.838472   \n",
      "\n",
      "    difference  \n",
      "0    10.765827  \n",
      "1   -12.271155  \n",
      "2    -2.660826  \n",
      "3    -4.072361  \n",
      "4   -20.345967  \n",
      "5    11.513358  \n",
      "6     6.336373  \n",
      "7     2.786180  \n",
      "8   -16.663393  \n",
      "9   107.012864  \n",
      "10   69.160798  \n",
      "11        -inf  \n",
      "12        -inf  \n",
      "13         inf  \n",
      "14  100.000000  \n",
      "15 -147.177763  \n",
      "16 -110.456262  \n",
      "17   55.508976  \n",
      "18  -21.078202  \n",
      "19  -62.706180  \n",
      "20    4.099538  \n",
      "21   -1.568322  \n",
      "22  -17.873415  \n",
      "23  -13.710153  \n",
      "24  105.296537  \n",
      "25   79.596972  \n",
      "26   78.457036  \n",
      "27        -inf  \n",
      "28        -inf  \n",
      "29 -145.665902  \n",
      "30   12.303361  \n",
      "31  -16.599669  \n",
      "32  -93.634572  \n",
      "33  -32.876327  \n",
      "34  -25.954748  \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 994, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 840, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 580, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 549, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 391, in format\n",
      "    return self._fmt % record.__dict__\n",
      "KeyError: 'status'\n",
      "Call stack:\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelapp.py\", line 505, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/platform/asyncio.py\", line 132, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 438, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 1451, in _run_once\n",
      "    handle._run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/events.py\", line 145, in _run\n",
      "    self._callback(*self._args)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/ioloop.py\", line 758, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/stack_context.py\", line 300, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1233, in inner\n",
      "    self.run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1147, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 357, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 267, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 534, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/ipkernel.py\", line 294, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2819, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2845, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/async_helpers.py\", line 67, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3020, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3185, in run_ast_nodes\n",
      "    if (yield from self.run_code(code, result)):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3267, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-9-316710011e92>\", line 1, in <module>\n",
      "    message, data = sqlConnection.execute_script(saveToTable='Kickboxing_attendance.forecast')\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 123, in execute_script\n",
      "    nbRowInserts=nbRowInserts)\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 476, in execute_script\n",
      "    chunksize=nbRowInserts\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/core/frame.py\", line 1418, in to_gbq\n",
      "    verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/io/gbq.py\", line 162, in to_gbq\n",
      "    credentials=credentials, verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1024, in to_gbq\n",
      "    if table.exists(table_id):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1122, in exists\n",
      "    self.client.get_table(table_ref)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 434, in get_table\n",
      "    api_response = self._call_api(retry, method=\"GET\", path=table_ref.path)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 381, in _call_api\n",
      "    return call()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/retry.py\", line 260, in retry_wrapped_func\n",
      "    on_error=on_error,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/retry.py\", line 177, in retry_target\n",
      "    return target()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 290, in api_request\n",
      "    headers=headers, target_object=_target_object)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 183, in _make_request\n",
      "    return self._do_request(method, url, headers, data, target_object)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 211, in _do_request\n",
      "    return self.http.request(\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 73, in http\n",
      "    return self._client._http\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/client.py\", line 151, in _http\n",
      "    self._credentials))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/auth/transport/requests.py\", line 172, in __init__\n",
      "    retry_adapter = requests.adapters.HTTPAdapter(max_retries=3)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/adapters.py\", line 119, in __init__\n",
      "    self.max_retries = Retry.from_int(max_retries)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/util/retry.py\", line 210, in from_int\n",
      "    log.debug(\"Converted retries value: %r -> %r\", retries, new_retries)\n",
      "Message: 'Converted retries value: %r -> %r'\n",
      "Arguments: (3, Retry(total=3, connect=None, read=None, redirect=None, status=None))\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 994, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 840, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 580, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 549, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 391, in format\n",
      "    return self._fmt % record.__dict__\n",
      "KeyError: 'status'\n",
      "Call stack:\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelapp.py\", line 505, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/platform/asyncio.py\", line 132, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 438, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 1451, in _run_once\n",
      "    handle._run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/events.py\", line 145, in _run\n",
      "    self._callback(*self._args)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/ioloop.py\", line 758, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/stack_context.py\", line 300, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1233, in inner\n",
      "    self.run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1147, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 357, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 267, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 534, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/ipkernel.py\", line 294, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2819, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2845, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/async_helpers.py\", line 67, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3020, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3185, in run_ast_nodes\n",
      "    if (yield from self.run_code(code, result)):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3267, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-9-316710011e92>\", line 1, in <module>\n",
      "    message, data = sqlConnection.execute_script(saveToTable='Kickboxing_attendance.forecast')\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 123, in execute_script\n",
      "    nbRowInserts=nbRowInserts)\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 476, in execute_script\n",
      "    chunksize=nbRowInserts\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/core/frame.py\", line 1418, in to_gbq\n",
      "    verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/io/gbq.py\", line 162, in to_gbq\n",
      "    credentials=credentials, verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1024, in to_gbq\n",
      "    if table.exists(table_id):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1122, in exists\n",
      "    self.client.get_table(table_ref)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 434, in get_table\n",
      "    api_response = self._call_api(retry, method=\"GET\", path=table_ref.path)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 381, in _call_api\n",
      "    return call()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/retry.py\", line 260, in retry_wrapped_func\n",
      "    on_error=on_error,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/retry.py\", line 177, in retry_target\n",
      "    return target()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 290, in api_request\n",
      "    headers=headers, target_object=_target_object)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 183, in _make_request\n",
      "    return self._do_request(method, url, headers, data, target_object)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 212, in _do_request\n",
      "    url=url, method=method, headers=headers, data=data)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/auth/transport/requests.py\", line 201, in request\n",
      "    method, url, data=data, headers=request_headers, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 588, in urlopen\n",
      "    conn = self._get_conn(timeout=pool_timeout)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 248, in _get_conn\n",
      "    return conn or self._new_conn()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 813, in _new_conn\n",
      "    self.num_connections, self.host, self.port or \"443\")\n",
      "Message: 'Starting new HTTPS connection (%d): %s:%s'\n",
      "Arguments: (1, 'www.googleapis.com', 443)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 994, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 840, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 580, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 549, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 391, in format\n",
      "    return self._fmt % record.__dict__\n",
      "KeyError: 'status'\n",
      "Call stack:\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelapp.py\", line 505, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/platform/asyncio.py\", line 132, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 438, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 1451, in _run_once\n",
      "    handle._run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/events.py\", line 145, in _run\n",
      "    self._callback(*self._args)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/ioloop.py\", line 758, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/stack_context.py\", line 300, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1233, in inner\n",
      "    self.run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1147, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 357, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 267, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 534, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/ipkernel.py\", line 294, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2819, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2845, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/async_helpers.py\", line 67, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3020, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3185, in run_ast_nodes\n",
      "    if (yield from self.run_code(code, result)):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3267, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-9-316710011e92>\", line 1, in <module>\n",
      "    message, data = sqlConnection.execute_script(saveToTable='Kickboxing_attendance.forecast')\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 123, in execute_script\n",
      "    nbRowInserts=nbRowInserts)\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 476, in execute_script\n",
      "    chunksize=nbRowInserts\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/core/frame.py\", line 1418, in to_gbq\n",
      "    verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/io/gbq.py\", line 162, in to_gbq\n",
      "    credentials=credentials, verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1024, in to_gbq\n",
      "    if table.exists(table_id):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1122, in exists\n",
      "    self.client.get_table(table_ref)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 434, in get_table\n",
      "    api_response = self._call_api(retry, method=\"GET\", path=table_ref.path)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 381, in _call_api\n",
      "    return call()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/retry.py\", line 260, in retry_wrapped_func\n",
      "    on_error=on_error,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/retry.py\", line 177, in retry_target\n",
      "    return target()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 290, in api_request\n",
      "    headers=headers, target_object=_target_object)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 183, in _make_request\n",
      "    return self._do_request(method, url, headers, data, target_object)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 212, in _do_request\n",
      "    url=url, method=method, headers=headers, data=data)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/auth/transport/requests.py\", line 201, in request\n",
      "    method, url, data=data, headers=request_headers, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 600, in urlopen\n",
      "    chunked=chunked)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 393, in _make_request\n",
      "    httplib_response.length)\n",
      "Message: '%s://%s:%s \"%s %s %s\" %s %s'\n",
      "Arguments: ('https', 'www.googleapis.com', 443, 'GET', '/bigquery/v2/projects/crafty-ring-247514/datasets/Kickboxing_attendance/tables/forecast', 'HTTP/1.1', 404, None)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 994, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 840, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 580, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 549, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 391, in format\n",
      "    return self._fmt % record.__dict__\n",
      "KeyError: 'status'\n",
      "Call stack:\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelapp.py\", line 505, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/platform/asyncio.py\", line 132, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 438, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 1451, in _run_once\n",
      "    handle._run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/events.py\", line 145, in _run\n",
      "    self._callback(*self._args)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/ioloop.py\", line 758, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/stack_context.py\", line 300, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1233, in inner\n",
      "    self.run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1147, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 357, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 267, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 534, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/ipkernel.py\", line 294, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2819, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2845, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/async_helpers.py\", line 67, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3020, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3185, in run_ast_nodes\n",
      "    if (yield from self.run_code(code, result)):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3267, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-9-316710011e92>\", line 1, in <module>\n",
      "    message, data = sqlConnection.execute_script(saveToTable='Kickboxing_attendance.forecast')\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 123, in execute_script\n",
      "    nbRowInserts=nbRowInserts)\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 476, in execute_script\n",
      "    chunksize=nbRowInserts\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/core/frame.py\", line 1418, in to_gbq\n",
      "    verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/io/gbq.py\", line 162, in to_gbq\n",
      "    credentials=credentials, verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1046, in to_gbq\n",
      "    table.create(table_id, table_schema)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1143, in create\n",
      "    if self.exists(table_id):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1122, in exists\n",
      "    self.client.get_table(table_ref)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 434, in get_table\n",
      "    api_response = self._call_api(retry, method=\"GET\", path=table_ref.path)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 381, in _call_api\n",
      "    return call()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/retry.py\", line 260, in retry_wrapped_func\n",
      "    on_error=on_error,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/retry.py\", line 177, in retry_target\n",
      "    return target()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 290, in api_request\n",
      "    headers=headers, target_object=_target_object)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 183, in _make_request\n",
      "    return self._do_request(method, url, headers, data, target_object)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 212, in _do_request\n",
      "    url=url, method=method, headers=headers, data=data)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/auth/transport/requests.py\", line 201, in request\n",
      "    method, url, data=data, headers=request_headers, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 600, in urlopen\n",
      "    chunked=chunked)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 393, in _make_request\n",
      "    httplib_response.length)\n",
      "Message: '%s://%s:%s \"%s %s %s\" %s %s'\n",
      "Arguments: ('https', 'www.googleapis.com', 443, 'GET', '/bigquery/v2/projects/crafty-ring-247514/datasets/Kickboxing_attendance/tables/forecast', 'HTTP/1.1', 404, None)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 994, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 840, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 580, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 549, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 391, in format\n",
      "    return self._fmt % record.__dict__\n",
      "KeyError: 'status'\n",
      "Call stack:\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelapp.py\", line 505, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/platform/asyncio.py\", line 132, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 438, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 1451, in _run_once\n",
      "    handle._run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/events.py\", line 145, in _run\n",
      "    self._callback(*self._args)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/ioloop.py\", line 758, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/stack_context.py\", line 300, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1233, in inner\n",
      "    self.run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1147, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 357, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 267, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 534, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/ipkernel.py\", line 294, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2819, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2845, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/async_helpers.py\", line 67, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3020, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3185, in run_ast_nodes\n",
      "    if (yield from self.run_code(code, result)):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3267, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-9-316710011e92>\", line 1, in <module>\n",
      "    message, data = sqlConnection.execute_script(saveToTable='Kickboxing_attendance.forecast')\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 123, in execute_script\n",
      "    nbRowInserts=nbRowInserts)\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 476, in execute_script\n",
      "    chunksize=nbRowInserts\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/core/frame.py\", line 1418, in to_gbq\n",
      "    verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/io/gbq.py\", line 162, in to_gbq\n",
      "    credentials=credentials, verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1046, in to_gbq\n",
      "    table.create(table_id, table_schema)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1149, in create\n",
      "    self.dataset_id\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1232, in exists\n",
      "    self.client.get_dataset(self.client.dataset(dataset_id))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 407, in get_dataset\n",
      "    api_response = self._call_api(retry, method=\"GET\", path=dataset_ref.path)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 381, in _call_api\n",
      "    return call()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/retry.py\", line 260, in retry_wrapped_func\n",
      "    on_error=on_error,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/retry.py\", line 177, in retry_target\n",
      "    return target()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 290, in api_request\n",
      "    headers=headers, target_object=_target_object)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 183, in _make_request\n",
      "    return self._do_request(method, url, headers, data, target_object)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 211, in _do_request\n",
      "    return self.http.request(\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 73, in http\n",
      "    return self._client._http\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/client.py\", line 151, in _http\n",
      "    self._credentials))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/auth/transport/requests.py\", line 172, in __init__\n",
      "    retry_adapter = requests.adapters.HTTPAdapter(max_retries=3)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/adapters.py\", line 119, in __init__\n",
      "    self.max_retries = Retry.from_int(max_retries)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/util/retry.py\", line 210, in from_int\n",
      "    log.debug(\"Converted retries value: %r -> %r\", retries, new_retries)\n",
      "Message: 'Converted retries value: %r -> %r'\n",
      "Arguments: (3, Retry(total=3, connect=None, read=None, redirect=None, status=None))\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 994, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 840, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 580, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 549, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 391, in format\n",
      "    return self._fmt % record.__dict__\n",
      "KeyError: 'status'\n",
      "Call stack:\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelapp.py\", line 505, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/platform/asyncio.py\", line 132, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 438, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 1451, in _run_once\n",
      "    handle._run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/events.py\", line 145, in _run\n",
      "    self._callback(*self._args)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/ioloop.py\", line 758, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/stack_context.py\", line 300, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1233, in inner\n",
      "    self.run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1147, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 357, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 267, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 534, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/ipkernel.py\", line 294, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2819, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2845, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/async_helpers.py\", line 67, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3020, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3185, in run_ast_nodes\n",
      "    if (yield from self.run_code(code, result)):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3267, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-9-316710011e92>\", line 1, in <module>\n",
      "    message, data = sqlConnection.execute_script(saveToTable='Kickboxing_attendance.forecast')\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 123, in execute_script\n",
      "    nbRowInserts=nbRowInserts)\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 476, in execute_script\n",
      "    chunksize=nbRowInserts\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/core/frame.py\", line 1418, in to_gbq\n",
      "    verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/io/gbq.py\", line 162, in to_gbq\n",
      "    credentials=credentials, verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1046, in to_gbq\n",
      "    table.create(table_id, table_schema)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1149, in create\n",
      "    self.dataset_id\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1232, in exists\n",
      "    self.client.get_dataset(self.client.dataset(dataset_id))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 407, in get_dataset\n",
      "    api_response = self._call_api(retry, method=\"GET\", path=dataset_ref.path)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 381, in _call_api\n",
      "    return call()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/retry.py\", line 260, in retry_wrapped_func\n",
      "    on_error=on_error,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/retry.py\", line 177, in retry_target\n",
      "    return target()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 290, in api_request\n",
      "    headers=headers, target_object=_target_object)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 183, in _make_request\n",
      "    return self._do_request(method, url, headers, data, target_object)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 212, in _do_request\n",
      "    url=url, method=method, headers=headers, data=data)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/auth/transport/requests.py\", line 201, in request\n",
      "    method, url, data=data, headers=request_headers, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 588, in urlopen\n",
      "    conn = self._get_conn(timeout=pool_timeout)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 248, in _get_conn\n",
      "    return conn or self._new_conn()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 813, in _new_conn\n",
      "    self.num_connections, self.host, self.port or \"443\")\n",
      "Message: 'Starting new HTTPS connection (%d): %s:%s'\n",
      "Arguments: (1, 'www.googleapis.com', 443)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 994, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 840, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 580, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 549, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 391, in format\n",
      "    return self._fmt % record.__dict__\n",
      "KeyError: 'status'\n",
      "Call stack:\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelapp.py\", line 505, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/platform/asyncio.py\", line 132, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 438, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 1451, in _run_once\n",
      "    handle._run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/events.py\", line 145, in _run\n",
      "    self._callback(*self._args)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/ioloop.py\", line 758, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/stack_context.py\", line 300, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1233, in inner\n",
      "    self.run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1147, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 357, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 267, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 534, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/ipkernel.py\", line 294, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2819, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2845, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/async_helpers.py\", line 67, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3020, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3185, in run_ast_nodes\n",
      "    if (yield from self.run_code(code, result)):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3267, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-9-316710011e92>\", line 1, in <module>\n",
      "    message, data = sqlConnection.execute_script(saveToTable='Kickboxing_attendance.forecast')\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 123, in execute_script\n",
      "    nbRowInserts=nbRowInserts)\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 476, in execute_script\n",
      "    chunksize=nbRowInserts\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/core/frame.py\", line 1418, in to_gbq\n",
      "    verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/io/gbq.py\", line 162, in to_gbq\n",
      "    credentials=credentials, verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1046, in to_gbq\n",
      "    table.create(table_id, table_schema)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1149, in create\n",
      "    self.dataset_id\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1232, in exists\n",
      "    self.client.get_dataset(self.client.dataset(dataset_id))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 407, in get_dataset\n",
      "    api_response = self._call_api(retry, method=\"GET\", path=dataset_ref.path)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 381, in _call_api\n",
      "    return call()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/retry.py\", line 260, in retry_wrapped_func\n",
      "    on_error=on_error,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/retry.py\", line 177, in retry_target\n",
      "    return target()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 290, in api_request\n",
      "    headers=headers, target_object=_target_object)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 183, in _make_request\n",
      "    return self._do_request(method, url, headers, data, target_object)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 212, in _do_request\n",
      "    url=url, method=method, headers=headers, data=data)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/auth/transport/requests.py\", line 201, in request\n",
      "    method, url, data=data, headers=request_headers, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 600, in urlopen\n",
      "    chunked=chunked)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 393, in _make_request\n",
      "    httplib_response.length)\n",
      "Message: '%s://%s:%s \"%s %s %s\" %s %s'\n",
      "Arguments: ('https', 'www.googleapis.com', 443, 'GET', '/bigquery/v2/projects/crafty-ring-247514/datasets/Kickboxing_attendance', 'HTTP/1.1', 200, None)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 994, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 840, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 580, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 549, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 391, in format\n",
      "    return self._fmt % record.__dict__\n",
      "KeyError: 'status'\n",
      "Call stack:\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelapp.py\", line 505, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/platform/asyncio.py\", line 132, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 438, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 1451, in _run_once\n",
      "    handle._run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/events.py\", line 145, in _run\n",
      "    self._callback(*self._args)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/ioloop.py\", line 758, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/stack_context.py\", line 300, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1233, in inner\n",
      "    self.run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1147, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 357, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 267, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 534, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/ipkernel.py\", line 294, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2819, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2845, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/async_helpers.py\", line 67, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3020, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3185, in run_ast_nodes\n",
      "    if (yield from self.run_code(code, result)):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3267, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-9-316710011e92>\", line 1, in <module>\n",
      "    message, data = sqlConnection.execute_script(saveToTable='Kickboxing_attendance.forecast')\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 123, in execute_script\n",
      "    nbRowInserts=nbRowInserts)\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 476, in execute_script\n",
      "    chunksize=nbRowInserts\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/core/frame.py\", line 1418, in to_gbq\n",
      "    verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/io/gbq.py\", line 162, in to_gbq\n",
      "    credentials=credentials, verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1046, in to_gbq\n",
      "    table.create(table_id, table_schema)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1172, in create\n",
      "    self.client.create_table(table)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 373, in create_table\n",
      "    method=\"POST\", path=path, data=table.to_api_repr()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 290, in api_request\n",
      "    headers=headers, target_object=_target_object)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 183, in _make_request\n",
      "    return self._do_request(method, url, headers, data, target_object)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 212, in _do_request\n",
      "    url=url, method=method, headers=headers, data=data)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/auth/transport/requests.py\", line 201, in request\n",
      "    method, url, data=data, headers=request_headers, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 600, in urlopen\n",
      "    chunked=chunked)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 393, in _make_request\n",
      "    httplib_response.length)\n",
      "Message: '%s://%s:%s \"%s %s %s\" %s %s'\n",
      "Arguments: ('https', 'www.googleapis.com', 443, 'POST', '/bigquery/v2/projects/crafty-ring-247514/datasets/Kickboxing_attendance/tables', 'HTTP/1.1', 200, None)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 994, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 840, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 580, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 549, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 391, in format\n",
      "    return self._fmt % record.__dict__\n",
      "KeyError: 'status'\n",
      "Call stack:\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelapp.py\", line 505, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/platform/asyncio.py\", line 132, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 438, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 1451, in _run_once\n",
      "    handle._run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/events.py\", line 145, in _run\n",
      "    self._callback(*self._args)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/ioloop.py\", line 758, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/stack_context.py\", line 300, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1233, in inner\n",
      "    self.run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1147, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 357, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 267, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 534, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/ipkernel.py\", line 294, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2819, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2845, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/async_helpers.py\", line 67, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3020, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3185, in run_ast_nodes\n",
      "    if (yield from self.run_code(code, result)):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3267, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-9-316710011e92>\", line 1, in <module>\n",
      "    message, data = sqlConnection.execute_script(saveToTable='Kickboxing_attendance.forecast')\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 123, in execute_script\n",
      "    nbRowInserts=nbRowInserts)\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 476, in execute_script\n",
      "    chunksize=nbRowInserts\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/core/frame.py\", line 1418, in to_gbq\n",
      "    verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/io/gbq.py\", line 162, in to_gbq\n",
      "    credentials=credentials, verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1054, in to_gbq\n",
      "    progress_bar=progress_bar,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 524, in load_data\n",
      "    ((total_rows - remaining_rows) * 100) / total_rows\n",
      "Message: '\\rLoad is 100.0% Complete'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 994, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 840, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 580, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 549, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 391, in format\n",
      "    return self._fmt % record.__dict__\n",
      "KeyError: 'status'\n",
      "Call stack:\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelapp.py\", line 505, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/platform/asyncio.py\", line 132, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 438, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 1451, in _run_once\n",
      "    handle._run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/events.py\", line 145, in _run\n",
      "    self._callback(*self._args)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/ioloop.py\", line 758, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/stack_context.py\", line 300, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1233, in inner\n",
      "    self.run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1147, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 357, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 267, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 534, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/ipkernel.py\", line 294, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2819, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2845, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/async_helpers.py\", line 67, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3020, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3185, in run_ast_nodes\n",
      "    if (yield from self.run_code(code, result)):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3267, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-9-316710011e92>\", line 1, in <module>\n",
      "    message, data = sqlConnection.execute_script(saveToTable='Kickboxing_attendance.forecast')\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 123, in execute_script\n",
      "    nbRowInserts=nbRowInserts)\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 476, in execute_script\n",
      "    chunksize=nbRowInserts\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/core/frame.py\", line 1418, in to_gbq\n",
      "    verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/io/gbq.py\", line 162, in to_gbq\n",
      "    credentials=credentials, verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1054, in to_gbq\n",
      "    progress_bar=progress_bar,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 521, in load_data\n",
      "    for remaining_rows in chunks:\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/load.py\", line 87, in load_chunks\n",
      "    location=location,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 1026, in load_table_from_file\n",
      "    file_obj, job_resource, num_retries\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 1131, in _do_resumable_upload\n",
      "    stream, metadata, num_retries\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 1161, in _initiate_resumable_upload\n",
      "    transport = self._http\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/client.py\", line 151, in _http\n",
      "    self._credentials))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/auth/transport/requests.py\", line 172, in __init__\n",
      "    retry_adapter = requests.adapters.HTTPAdapter(max_retries=3)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/adapters.py\", line 119, in __init__\n",
      "    self.max_retries = Retry.from_int(max_retries)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/util/retry.py\", line 210, in from_int\n",
      "    log.debug(\"Converted retries value: %r -> %r\", retries, new_retries)\n",
      "Message: 'Converted retries value: %r -> %r'\n",
      "Arguments: (3, Retry(total=3, connect=None, read=None, redirect=None, status=None))\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 994, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 840, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 580, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 549, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 391, in format\n",
      "    return self._fmt % record.__dict__\n",
      "KeyError: 'status'\n",
      "Call stack:\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelapp.py\", line 505, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/platform/asyncio.py\", line 132, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 438, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 1451, in _run_once\n",
      "    handle._run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/events.py\", line 145, in _run\n",
      "    self._callback(*self._args)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/ioloop.py\", line 758, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/stack_context.py\", line 300, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1233, in inner\n",
      "    self.run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1147, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 357, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 267, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 534, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/ipkernel.py\", line 294, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2819, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2845, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/async_helpers.py\", line 67, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3020, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3185, in run_ast_nodes\n",
      "    if (yield from self.run_code(code, result)):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3267, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-9-316710011e92>\", line 1, in <module>\n",
      "    message, data = sqlConnection.execute_script(saveToTable='Kickboxing_attendance.forecast')\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 123, in execute_script\n",
      "    nbRowInserts=nbRowInserts)\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 476, in execute_script\n",
      "    chunksize=nbRowInserts\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/core/frame.py\", line 1418, in to_gbq\n",
      "    verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/io/gbq.py\", line 162, in to_gbq\n",
      "    credentials=credentials, verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1054, in to_gbq\n",
      "    progress_bar=progress_bar,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 521, in load_data\n",
      "    for remaining_rows in chunks:\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/load.py\", line 87, in load_chunks\n",
      "    location=location,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 1026, in load_table_from_file\n",
      "    file_obj, job_resource, num_retries\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 1131, in _do_resumable_upload\n",
      "    stream, metadata, num_retries\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 1174, in _initiate_resumable_upload\n",
      "    transport, stream, metadata, _GENERIC_CONTENT_TYPE, stream_final=False\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/resumable_media/requests/upload.py\", line 326, in initiate\n",
      "    retry_strategy=self._retry_strategy)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/resumable_media/requests/_helpers.py\", line 101, in http_request\n",
      "    func, RequestsMixin._get_status_code, retry_strategy)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/resumable_media/_helpers.py\", line 146, in wait_and_retry\n",
      "    response = func()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/auth/transport/requests.py\", line 201, in request\n",
      "    method, url, data=data, headers=request_headers, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 588, in urlopen\n",
      "    conn = self._get_conn(timeout=pool_timeout)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 248, in _get_conn\n",
      "    return conn or self._new_conn()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 813, in _new_conn\n",
      "    self.num_connections, self.host, self.port or \"443\")\n",
      "Message: 'Starting new HTTPS connection (%d): %s:%s'\n",
      "Arguments: (1, 'www.googleapis.com', 443)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 994, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 840, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 580, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 549, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 391, in format\n",
      "    return self._fmt % record.__dict__\n",
      "KeyError: 'status'\n",
      "Call stack:\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelapp.py\", line 505, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/platform/asyncio.py\", line 132, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 438, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 1451, in _run_once\n",
      "    handle._run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/events.py\", line 145, in _run\n",
      "    self._callback(*self._args)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/ioloop.py\", line 758, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/stack_context.py\", line 300, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1233, in inner\n",
      "    self.run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1147, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 357, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 267, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 534, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/ipkernel.py\", line 294, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2819, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2845, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/async_helpers.py\", line 67, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3020, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3185, in run_ast_nodes\n",
      "    if (yield from self.run_code(code, result)):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3267, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-9-316710011e92>\", line 1, in <module>\n",
      "    message, data = sqlConnection.execute_script(saveToTable='Kickboxing_attendance.forecast')\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 123, in execute_script\n",
      "    nbRowInserts=nbRowInserts)\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 476, in execute_script\n",
      "    chunksize=nbRowInserts\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/core/frame.py\", line 1418, in to_gbq\n",
      "    verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/io/gbq.py\", line 162, in to_gbq\n",
      "    credentials=credentials, verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1054, in to_gbq\n",
      "    progress_bar=progress_bar,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 521, in load_data\n",
      "    for remaining_rows in chunks:\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/load.py\", line 87, in load_chunks\n",
      "    location=location,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 1026, in load_table_from_file\n",
      "    file_obj, job_resource, num_retries\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 1131, in _do_resumable_upload\n",
      "    stream, metadata, num_retries\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 1174, in _initiate_resumable_upload\n",
      "    transport, stream, metadata, _GENERIC_CONTENT_TYPE, stream_final=False\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/resumable_media/requests/upload.py\", line 326, in initiate\n",
      "    retry_strategy=self._retry_strategy)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/resumable_media/requests/_helpers.py\", line 101, in http_request\n",
      "    func, RequestsMixin._get_status_code, retry_strategy)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/resumable_media/_helpers.py\", line 146, in wait_and_retry\n",
      "    response = func()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/auth/transport/requests.py\", line 201, in request\n",
      "    method, url, data=data, headers=request_headers, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 600, in urlopen\n",
      "    chunked=chunked)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 393, in _make_request\n",
      "    httplib_response.length)\n",
      "Message: '%s://%s:%s \"%s %s %s\" %s %s'\n",
      "Arguments: ('https', 'www.googleapis.com', 443, 'POST', '/upload/bigquery/v2/projects/crafty-ring-247514/jobs?uploadType=resumable', 'HTTP/1.1', 200, 0)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 994, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 840, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 580, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 549, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 391, in format\n",
      "    return self._fmt % record.__dict__\n",
      "KeyError: 'status'\n",
      "Call stack:\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelapp.py\", line 505, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/platform/asyncio.py\", line 132, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 438, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 1451, in _run_once\n",
      "    handle._run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/events.py\", line 145, in _run\n",
      "    self._callback(*self._args)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/ioloop.py\", line 758, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/stack_context.py\", line 300, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1233, in inner\n",
      "    self.run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1147, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 357, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 267, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 534, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/ipkernel.py\", line 294, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2819, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2845, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/async_helpers.py\", line 67, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3020, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3185, in run_ast_nodes\n",
      "    if (yield from self.run_code(code, result)):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3267, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-9-316710011e92>\", line 1, in <module>\n",
      "    message, data = sqlConnection.execute_script(saveToTable='Kickboxing_attendance.forecast')\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 123, in execute_script\n",
      "    nbRowInserts=nbRowInserts)\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 476, in execute_script\n",
      "    chunksize=nbRowInserts\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/core/frame.py\", line 1418, in to_gbq\n",
      "    verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/io/gbq.py\", line 162, in to_gbq\n",
      "    credentials=credentials, verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1054, in to_gbq\n",
      "    progress_bar=progress_bar,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 521, in load_data\n",
      "    for remaining_rows in chunks:\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/load.py\", line 87, in load_chunks\n",
      "    location=location,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 1026, in load_table_from_file\n",
      "    file_obj, job_resource, num_retries\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 1135, in _do_resumable_upload\n",
      "    response = upload.transmit_next_chunk(transport)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/resumable_media/requests/upload.py\", line 395, in transmit_next_chunk\n",
      "    retry_strategy=self._retry_strategy)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/resumable_media/requests/_helpers.py\", line 101, in http_request\n",
      "    func, RequestsMixin._get_status_code, retry_strategy)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/resumable_media/_helpers.py\", line 146, in wait_and_retry\n",
      "    response = func()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/auth/transport/requests.py\", line 201, in request\n",
      "    method, url, data=data, headers=request_headers, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 600, in urlopen\n",
      "    chunked=chunked)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 393, in _make_request\n",
      "    httplib_response.length)\n",
      "Message: '%s://%s:%s \"%s %s %s\" %s %s'\n",
      "Arguments: ('https', 'www.googleapis.com', 443, 'PUT', '/upload/bigquery/v2/projects/crafty-ring-247514/jobs?uploadType=resumable&upload_id=AEnB2UqecgxCCIDtED-VTmncnMootYSI9ZZifWn_z40ryZ0ua-nUtpm6XJw2LftZtG-poCrvS5y75t7A3Bn5WkHAx_pUQz3sXg', 'HTTP/1.1', 200, 1563)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 994, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 840, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 580, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 549, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 391, in format\n",
      "    return self._fmt % record.__dict__\n",
      "KeyError: 'status'\n",
      "Call stack:\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelapp.py\", line 505, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/platform/asyncio.py\", line 132, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 438, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 1451, in _run_once\n",
      "    handle._run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/events.py\", line 145, in _run\n",
      "    self._callback(*self._args)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/ioloop.py\", line 758, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/stack_context.py\", line 300, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1233, in inner\n",
      "    self.run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1147, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 357, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 267, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 534, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/ipkernel.py\", line 294, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2819, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2845, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/async_helpers.py\", line 67, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3020, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3185, in run_ast_nodes\n",
      "    if (yield from self.run_code(code, result)):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3267, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-9-316710011e92>\", line 1, in <module>\n",
      "    message, data = sqlConnection.execute_script(saveToTable='Kickboxing_attendance.forecast')\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 123, in execute_script\n",
      "    nbRowInserts=nbRowInserts)\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 476, in execute_script\n",
      "    chunksize=nbRowInserts\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/core/frame.py\", line 1418, in to_gbq\n",
      "    verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/io/gbq.py\", line 162, in to_gbq\n",
      "    credentials=credentials, verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1054, in to_gbq\n",
      "    progress_bar=progress_bar,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 521, in load_data\n",
      "    for remaining_rows in chunks:\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/load.py\", line 87, in load_chunks\n",
      "    location=location,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/job.py\", line 703, in result\n",
      "    return super(_AsyncJob, self).result(timeout=timeout)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/future/polling.py\", line 115, in result\n",
      "    self._blocking_poll(timeout=timeout)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/future/polling.py\", line 94, in _blocking_poll\n",
      "    retry_(self._done_or_raise)()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/retry.py\", line 260, in retry_wrapped_func\n",
      "    on_error=on_error,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/retry.py\", line 177, in retry_target\n",
      "    return target()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/future/polling.py\", line 73, in _done_or_raise\n",
      "    if not self.done():\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/job.py\", line 678, in done\n",
      "    self.reload(retry=retry)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/job.py\", line 610, in reload\n",
      "    retry, method=\"GET\", path=self.path, query_params=extra_params\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 381, in _call_api\n",
      "    return call()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/retry.py\", line 260, in retry_wrapped_func\n",
      "    on_error=on_error,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/retry.py\", line 177, in retry_target\n",
      "    return target()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 290, in api_request\n",
      "    headers=headers, target_object=_target_object)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 183, in _make_request\n",
      "    return self._do_request(method, url, headers, data, target_object)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 212, in _do_request\n",
      "    url=url, method=method, headers=headers, data=data)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/auth/transport/requests.py\", line 201, in request\n",
      "    method, url, data=data, headers=request_headers, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 600, in urlopen\n",
      "    chunked=chunked)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 393, in _make_request\n",
      "    httplib_response.length)\n",
      "Message: '%s://%s:%s \"%s %s %s\" %s %s'\n",
      "Arguments: ('https', 'www.googleapis.com', 443, 'GET', '/bigquery/v2/projects/crafty-ring-247514/jobs/65718139-cba3-4dc4-8e12-d6dfb1a73fe9?location=US', 'HTTP/1.1', 200, None)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 994, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 840, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 580, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 549, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 391, in format\n",
      "    return self._fmt % record.__dict__\n",
      "KeyError: 'status'\n",
      "Call stack:\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelapp.py\", line 505, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/platform/asyncio.py\", line 132, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 438, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 1451, in _run_once\n",
      "    handle._run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/events.py\", line 145, in _run\n",
      "    self._callback(*self._args)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/ioloop.py\", line 758, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/stack_context.py\", line 300, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1233, in inner\n",
      "    self.run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1147, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 357, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 267, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 534, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/ipkernel.py\", line 294, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2819, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2845, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/async_helpers.py\", line 67, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3020, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3185, in run_ast_nodes\n",
      "    if (yield from self.run_code(code, result)):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3267, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-9-316710011e92>\", line 1, in <module>\n",
      "    message, data = sqlConnection.execute_script(saveToTable='Kickboxing_attendance.forecast')\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 123, in execute_script\n",
      "    nbRowInserts=nbRowInserts)\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 476, in execute_script\n",
      "    chunksize=nbRowInserts\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/core/frame.py\", line 1418, in to_gbq\n",
      "    verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/io/gbq.py\", line 162, in to_gbq\n",
      "    credentials=credentials, verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1054, in to_gbq\n",
      "    progress_bar=progress_bar,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 521, in load_data\n",
      "    for remaining_rows in chunks:\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/load.py\", line 87, in load_chunks\n",
      "    location=location,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/job.py\", line 703, in result\n",
      "    return super(_AsyncJob, self).result(timeout=timeout)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/future/polling.py\", line 115, in result\n",
      "    self._blocking_poll(timeout=timeout)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/future/polling.py\", line 94, in _blocking_poll\n",
      "    retry_(self._done_or_raise)()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/retry.py\", line 260, in retry_wrapped_func\n",
      "    on_error=on_error,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/retry.py\", line 198, in retry_target\n",
      "    last_exc, sleep))\n",
      "Message: 'Retrying due to , sleeping 0.6s ...'\n",
      "Arguments: ()\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 994, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 840, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 580, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 549, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/logging/__init__.py\", line 391, in format\n",
      "    return self._fmt % record.__dict__\n",
      "KeyError: 'status'\n",
      "Call stack:\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelapp.py\", line 505, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/platform/asyncio.py\", line 132, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 438, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/base_events.py\", line 1451, in _run_once\n",
      "    handle._run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/asyncio/events.py\", line 145, in _run\n",
      "    self._callback(*self._args)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/ioloop.py\", line 758, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/stack_context.py\", line 300, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1233, in inner\n",
      "    self.run()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 1147, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 357, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 267, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 534, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/tornado/gen.py\", line 326, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/ipkernel.py\", line 294, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2819, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2845, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/async_helpers.py\", line 67, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3020, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3185, in run_ast_nodes\n",
      "    if (yield from self.run_code(code, result)):\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3267, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-9-316710011e92>\", line 1, in <module>\n",
      "    message, data = sqlConnection.execute_script(saveToTable='Kickboxing_attendance.forecast')\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 123, in execute_script\n",
      "    nbRowInserts=nbRowInserts)\n",
      "  File \"/Users/chrispickford/Documents/Coding/Python/Projects/DataCrane/dbutility/gnrl_database_interaction.py\", line 476, in execute_script\n",
      "    chunksize=nbRowInserts\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/core/frame.py\", line 1418, in to_gbq\n",
      "    verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas/io/gbq.py\", line 162, in to_gbq\n",
      "    credentials=credentials, verbose=verbose, private_key=private_key)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 1054, in to_gbq\n",
      "    progress_bar=progress_bar,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/gbq.py\", line 521, in load_data\n",
      "    for remaining_rows in chunks:\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/pandas_gbq/load.py\", line 87, in load_chunks\n",
      "    location=location,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/job.py\", line 703, in result\n",
      "    return super(_AsyncJob, self).result(timeout=timeout)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/future/polling.py\", line 115, in result\n",
      "    self._blocking_poll(timeout=timeout)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/future/polling.py\", line 94, in _blocking_poll\n",
      "    retry_(self._done_or_raise)()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/retry.py\", line 260, in retry_wrapped_func\n",
      "    on_error=on_error,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/retry.py\", line 177, in retry_target\n",
      "    return target()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/future/polling.py\", line 73, in _done_or_raise\n",
      "    if not self.done():\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/job.py\", line 678, in done\n",
      "    self.reload(retry=retry)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/job.py\", line 610, in reload\n",
      "    retry, method=\"GET\", path=self.path, query_params=extra_params\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/bigquery/client.py\", line 381, in _call_api\n",
      "    return call()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/retry.py\", line 260, in retry_wrapped_func\n",
      "    on_error=on_error,\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/api_core/retry.py\", line 177, in retry_target\n",
      "    return target()\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 290, in api_request\n",
      "    headers=headers, target_object=_target_object)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 183, in _make_request\n",
      "    return self._do_request(method, url, headers, data, target_object)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/cloud/_http.py\", line 212, in _do_request\n",
      "    url=url, method=method, headers=headers, data=data)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/google/auth/transport/requests.py\", line 201, in request\n",
      "    method, url, data=data, headers=request_headers, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/requests/adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 600, in urlopen\n",
      "    chunked=chunked)\n",
      "  File \"/anaconda3/envs/utilityPackages/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 393, in _make_request\n",
      "    httplib_response.length)\n",
      "Message: '%s://%s:%s \"%s %s %s\" %s %s'\n",
      "Arguments: ('https', 'www.googleapis.com', 443, 'GET', '/bigquery/v2/projects/crafty-ring-247514/jobs/65718139-cba3-4dc4-8e12-d6dfb1a73fe9?location=US', 'HTTP/1.1', 200, None)\n"
     ]
    }
   ],
   "source": [
    "message, data = sqlConnection.execute_script(saveToTable='Kickboxing_attendance.forecast')\n",
    "data"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Put code here"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "utilityPackages",
   "language": "python",
   "name": "utilitypackages"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.8"
  },
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": false,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": false
  },
  "varInspector": {
   "cols": {
    "lenName": 16,
    "lenType": 16,
    "lenVar": 40
   },
   "kernels_config": {
    "python": {
     "delete_cmd_postfix": "",
     "delete_cmd_prefix": "del ",
     "library": "var_list.py",
     "varRefreshCmd": "print(var_dic_list())"
    },
    "r": {
     "delete_cmd_postfix": ") ",
     "delete_cmd_prefix": "rm(",
     "library": "var_list.r",
     "varRefreshCmd": "cat(var_dic_list()) "
    }
   },
   "types_to_exclude": [
    "module",
    "function",
    "builtin_function_or_method",
    "instance",
    "_Feature"
   ],
   "window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
